### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by tit0n** [1N3/HTTPoxyScan#1]
For some reason you create an ssl context (ctx) 

`20 ctx = ssl.create_default_context()`
`21 ctx.check_hostname = False`
`22 ctx.verify_mode = ssl.CERT_NONE`

But you are not using that context when calling 

` 
84 resp = urllib2.urlopen(req)
`

IMHO, the call should be smthg like this: 

`
84 resp = urllib2.urlopen(req, context=ctx)
`

This should avoid errors such as 
`urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>`

**Comment by 1N3** [comment]
hey, thanks for the heads up.. I'll look to implement the above shortly.

**Comment by LockeLamora** [comment]
Oh I have a pull request in for that

**Comment by 1N3** [comment]
This should be fixed now thanks to @LockeLamora. Closing out but let us know if you're still having issues.
